### ISSUE TITLE
Documentation for Module 1 needs to be updated to use Python 3.6 for development host.

### ISSUE THREAD

**Issue by TheAlanNix** [CiscoDevNet/dne-security-code#15]
On https://developer.cisco.com/learning/devnet-express/devnet-express-security-v1-1/dne-security-verify-v11/dne-security-verify-v-1-1/step/4

Step 3: Set up the Python Virtual Environment

The built-in CentOS RDP host actually needs "python3.6 -m venv venv" rather than "python3 -m venv venv"

**Comment by JPedro2** [comment]
Done! [LL guide updated](https://developer.cisco.com/learning/devnet-express/devnet-express-security-v1-1/dne-security-verify-v11/dne-security-verify-v-1-1/step/4) 😄
