### ISSUE TITLE
threat grid query time 180 days does not return data, needs to be changed to 360 days to work

### ISSUE THREAD

**Issue by chrivand** [CiscoDevNet/dne-security-code#19]
https://github.com/CiscoDevNet/dne-security-code/blob/v1.1-solutions/intro-threatgrid/threatgrid_ioc_query.py

**Comment by chrivand** [comment]
line 48

**Comment by JPedro2** [comment]
Fixed and tested. 360 days did not work either, `TIME_PERIOD` was changed to 500 days instead. This now returns data and matches the LL guide.
