### ISSUE TITLE
Replace SPARK_ACCESS_TOKEN and SPARK_ROOM_ID with ACCESS_TOKEN and ROOM_ID

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/dne-security-code#2]
Let's not keep propagating the wrong product name in the code.

**Comment by cmlccie** [comment]
I agree.  I'll update the sample code to use the `WEBEX_TEAMS_ACCESS_TOKEN` and the webexteamssdk as part of the `v1.1` update.

**Comment by cmlccie** [comment]
I have removed the references to Spark (leaving only one in the README file) and updated the code to use the webexteamssdk library.  This change will be released in `v1.1` of the learning track.

Please check out the release branch to see the code updates:
https://github.com/CiscoDevNet/dne-security-code/tree/v1.1
