### ISSUE TITLE
solution not correct of threat grid mission

### ISSUE THREAD

**Issue by chrivand** [CiscoDevNet/dne-security-code#33]
https://github.com/CiscoDevNet/dne-security-code/blob/v1.1-solutions/intro-threatgrid/mission/thgrid_mission.py

not correct, time should be wider. I changed it to 

"/search/submissions?after=2010-07-18T21:39:13Z&q={}"

then I got 44 hits, otherwise not much...

**Comment by annegentle** [comment]
@chrivand can you fix?

**Comment by chrivand** [comment]
Ok! Will check it out later

**Comment by chrivand** [comment]
https://github.com/CiscoDevNet/dne-security-code/pull/38
