### ISSUE TITLE
directory name standardization

### ISSUE THREAD

**Issue by fracaen** [CiscoDevNet/dne-security-code#6]
Could we please standardize the directory names?
Some have the "dne-security" prefix, eg dne-security-fdm-code
Some don't, eg amp-code

Can we please pick one or the other, and stick to it?
Thank you

**Comment by annegentle** [comment]
Thanks for reporting - moving it over to the code repo itself, makes sense to me.

**Comment by cmlccie** [comment]
@fracaen I am working this issue (folder name standardization) in the `v1.1` update that we are working on now.

**Comment by cmlccie** [comment]
I have standardized the directory names and project structure.  We will release this in `v1.1` of the learning track.

Please check out the release branch to see what the new folder structure looks like:
https://github.com/CiscoDevNet/dne-security-code/tree/v1.1

**Comment by cmlccie** [comment]
@fracaen check out the new directory structure and send me any feedback.  We are actively putting together the `v1.1` release.

**Comment by fracaen** [comment]
@cmlccie Perfect! Thank you.

**Comment by cmlccie** [comment]
This issue is resolved in v1.1.  Closing the issue so we can track our progress towards releasing the v1.1 update.
