### ISSUE TITLE
Remove refrence to "verify/" folder in readme file

### ISSUE THREAD

**Issue by nswiatec** [CiscoDevNet/dne-security-code#8]
in the table in the readme file, there's a reference to the "verify/" directory. This directory isn't present in the repo (and is probably a remainder from DNE DNA)

**Comment by cmlccie** [comment]
Yes, this definitely was a remainder from the Cisco DNA track.

***Note:*** We are in the process of doing some code refactoring and lab enhancements, which will include verification script(s) for the Security lab.  So, there will be a `verify/` directory shortly w/content.  😎

**Comment by annegentle** [comment]
There's now a `verify/` directory, so closing.
