### ISSUE TITLE
AMP step 2 JSON pretty print

### ISSUE THREAD

**Issue by fracaen** [CiscoDevNet/dne-security-code#9]
https://developer.cisco.com/learning/tracks/devnet-express-security/ampforendpoints/intro-into-amp-apis/step/2

Lab guide says:
"You should see a print out to the screen that looks similar to the section below: "
followed by JSON in a pretty format with colors

However, the code just outputs one big ugly blob of JSON text.

So either the lab guide needs to be corrected to match the code, or (preferably) the step2.py code needs to be corrected to json.dumps the JSON all pretty.

(thanks to John Frame for pointing it out)

**Comment by cmlccie** [comment]
@fracaen Thank you for reporting this issue.  These are precisely the sort of cleanliness and consistency corrections we are working to address with the v1.1 release.

**Comment by annegentle** [comment]
@oxsannikova Do you know where the code for this step lives? Maybe you already captured in your recent PR.

**Comment by veeratcisco** [comment]
@annegentle this all fixed since 1.1 release

**Comment by annegentle** [comment]
Great, closing.

**Comment by oxsannikova** [comment]
I have been working off of master branch. Was v1.1 branch merged?

BR,
O.

**Comment by annegentle** [comment]
The `master` branch and `v1.1` were synched last week, and we want to keep `master` up-to-date, so you're correct to push PRs to `master`.
